name: bsteele_music_tempo
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  logger:
  args:
  record:
  bsteele_bass_common:
    path: ../bsteele_bass_common
  bsteele_music_lib:
    path: ../bsteeleMusicLib/bsteele_music_lib

dev_dependencies:
  lints:
  test:

assets:
  - lib/assets/
